name: Test labels

on: 
  [push, pull_request]


jobs:
  nightly_build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: List lables in PR
      run: | 
        if: contains(github.event.pull_request.labels.*.name, 'nightly-build')
          echo "Nightly build label"
