name: Test labels

on: [push, pull_request]

jobs:
  nightly_build:
    runs-on: [ubuntu-latest]
    - name: List lables in PR
      run: | 
        echo "Labels in PR"
        y=${{ github.event.label.name }}
        echo $y
        x=${{ toJson(github.event.pull_request.labels.*.name) }}
        echo $x
